import type { Metadata } from 'next'
import Catalogue from '@/modules/catalogue/catalogue'

export const metadata: Metadata = {
  title: 'Renjana Furniture Catalogue',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <>
      <Catalogue />
    </>
  )
}
